-- CreateTable
CREATE TABLE `education` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `insituitionName` VARCHAR(100) NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `startYear` VARCHAR(100) NOT NULL,
    `endYear` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `major` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `degree` VARCHAR(100) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
